# Generated by Django 5.2.3 on 2025-06-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0002_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='history',
            field=models.JSONField(default=str),
        ),
        migrations.AlterField(
            model_name='chat',
            name='history_full',
            field=models.JSONField(default=str),
        ),
        migrations.AlterField(
            model_name='deletedchat',
            name='history',
            field=models.JSONField(default=str),
        ),
        migrations.AlterField(
            model_name='deletedchat',
            name='history_full',
            field=models.JSONField(default=str),
        ),
    ]
