# Generated by Django 5.2.3 on 2025-06-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0005_alter_chat_history_alter_chat_history_full_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='history',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='history_full',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='deletedchat',
            name='history',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='deletedchat',
            name='history_full',
            field=models.TextField(default='[]'),
        ),
    ]
