# Generated by Django 5.2.3 on 2025-06-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0006_alter_chat_history_alter_chat_history_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='model',
            field=models.CharField(default='gemini-2.5-pro', max_length=255),
        ),
    ]
