# Generated by Django 5.2.3 on 2025-06-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0007_chat_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
