# Generated by Django 5.2.3 on 2025-06-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0008_alter_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
