# Generated by Django 5.2.3 on 2025-07-03 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0009_alter_chat_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.TextField()),
            ],
        ),
    ]
